export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SELECTED_CATERGORY = 'SELECTED_CATERGORY';
export const GET_ALL_QUIZZESS_OF_SELECTED_CATEGORY = 'GET_ALL_QUIZZESS_OF_SELECTED_CATEGORY';
export const ADD_SELECTED_QUIZ_QUESTIONS = 'ADD_SELECTED_QUIZ_QUESTIONS';
